server:
  port: 80
  servlet:
    path: /
spring:
  thymeleaf:
    cache: false #关闭缓存
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/idea
    username: root
    password: 123456
mybatis:
  type-aliases-package: com.hp.pojo